CREATE DATABASE kydft;

USE kydft;

CREATE TABLE users(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	uname VARCHAR(50) NOT NULL,
	lastname VARCHAR(50) NOT NULL,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(100) NOT NULL
);

/*CREATE TABLE book(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	bname VARCHAR(100) NOT NULL,
	category VARCHAR(100) NOT NULL,
	cover VARCHAR(300) NOT NULL,
	user_id INT(11) NOT NULL,
	CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id)
);*/

CREATE TABLE pics(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	caption VARCHAR(300),
	description VARCHAR(3000),
	pic VARCHAR(300),
	category VARCHAR(20)
);

CREATE TABLE comments(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	cmnt VARCHAR(3000),
	user_id INT(11) NOT NULL,
	CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id),
	pic_id INT(11) NOT NULL,
	CONSTRAINT fk_pic FOREIGN KEY (pic_id) REFERENCES pics(id)
);

CREATE TABLE music(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	songname VARCHAR(60),
	artist VARCHAR(60),
	song VARCHAR(100),
	cover VARCHAR(100)
);